const GITHUB_ROOT = 'https://github.com/anonymaew/bdi-hackathon-2026-sampled-dataset/tree/main';

export const DATASET_TRACKS = [
    { key: 'Phenome', title: 'Phenome' },
    { key: 'Medical', title: 'Medical' },
    { key: 'Smart City', title: 'Smart City' },
];

export const datasetsData = [
    {
        slug: 'nmr-pattern',
        title: 'ชุดข้อมูลสเปกตรัม NMR สำหรับตรวจรูปแบบสารเคมี',
        track: 'Phenome',
        domains: ['Metabolomics', 'Compound Profiling'],
        sources: ['สถาบันฟีโนมแห่งชาติ'],
        totalRecords: null,
        sampledRecords: null,
        fileTypes: ['pdf'],
        summary: 'สัญญาณ NMR สองมิติ 20,000+ คอลัมน์/ตัวอย่าง ใช้ระบุชนิดและตำแหน่งสารประกอบทางเคมี',
        overviewLabel: '2D NMR Spectrum (PDF)',
        overviewDescription: '~20,000+ feature/ตัวอย่าง ข้อมูลดิบที่ต้องพึ่งผู้เชี่ยวชาญตีความ; ใช้ฝึก ML จำแนกสารประกอบ/ระบุ biomarker โดยลดความซับซ้อนของสัญญาณที่ซ้อนทับกัน',
        overview: [
            'ชุดข้อมูลสัญญาณ NMR (Nuclear Magnetic Resonance) แบบสองมิติ (2D) ที่มีประมาณ 20,000+ คอลัมน์ต่อตัวอย่าง ข้อมูลนี้แสดงรูปแบบสัญญาณของสารประกอบทางเคมีที่ตรวจพบในตัวอย่าง',
            'สัญญาณ NMR มีลักษณะเป็น spectrum ที่แสดง chemical shift (ppm) เป็นแกนหลัก โดยแต่ละตัวอย่างมีข้อมูลประมาณ 20,000++ จุดข้อมูล ซึ่งสอดคล้องกับตำแหน่งต่างๆ ใน spectrum',
        ],
        fields: [
            'ข้อมูล NMR Pattern ไม่มีฟิลด์แบบตาราง แต่มีลักษณะเป็น 2D matrix: ตัวอย่าง x สัญญาณ 20,000+ features ต่อตัวอย่าง',
        ],
        fileStructure: [
            { name: 'Domain_1_processed_NMR_spectrum.pdf', detail: 'PDF (ตัวอย่าง)' },
        ],
        analysisIdeas: [
            'Compound Classification: จำแนกรูปแบบสารแม่นยำจากสัญญาณ NMR',
            'Pattern Recognition / ML: ใช้ Machine Learning ระบุ compound อัตโนมัติ',
            'Feature Selection: เลือกตำแหน่งสัญญาณที่สำคัญที่สุด',
            'Biomarker Discovery: หา biomarker จากสัญญาณเฉพาะ',
            'Workflow Development: เสนอ workflow ประยุกต์ใช้ในการคัดกรองโรค',
        ],
        notes: [
            'ข้อมูลนี้เป็นข้อมูลดิบจาก NMR spectrum',
            'ความซับซ้อนของสัญญาณที่ซ้อนทับกันเป็นความท้าทายหลัก',
        ],
        githubUrl: `${GITHUB_ROOT}/nmr-pattern`,
    },
    {
        slug: 'nmr-result',
        title: 'ชุดข้อมูลสารเมตาบอไลต์ NMR สำหรับเปรียบเทียบผู้ป่วย',
        track: 'Phenome',
        domains: ['Metabolomics', 'Biomarker Discovery'],
        sources: ['สถาบันฟีโนมแห่งชาติ'],
        totalRecords: null,
        sampledRecords: 486,
        fileTypes: ['tsv'],
        summary: 'สารเมตาบอไลต์ abundance และ sample table สำหรับเปรียบเทียบผู้ป่วยกับกลุ่มควบคุม',
        overviewLabel: 'Metabolite Abundance (TSV, 486 samples, 20K+ columns)',
        overviewDescription: 'ค่าปริมาณสารเมตาบอไลต์ + metadata (อายุ, น้ำหนัก, การวินิจฉัย); เปรียบเทียบผู้ป่วยเบาหวาน+ความดัน vs. กลุ่มควบคุม; ใช้ค้นหา biomarker จำนวนน้อยที่สุดที่แยกโรคได้แม่นยำ',
        overview: [
            'ชุดข้อมูลผลลัพธ์การวิเคราะห์ NMR ที่เปรียบเทียบระหว่างผู้ป่วยเบาหวาน + ความดันโลหิตสูง กับกลุ่มควบคุม',
            'ข้อมูลประกอบด้วยผลการระบุสารประกอบและปริมาณ abundance ที่พบในแต่ละตัวอย่าง พร้อม sample table ที่เก็บข้อมูลเมตาของตัวอย่าง',
            'ข้อมูลนี้มีมากกว่า 20,000 คอลัมน์ของสัญญาณสารประกอบ พร้อมข้อมูลกายภาพและผลการวินิจฉัย',
        ],
        fields: [
            'Domain_2_NMR_results_MTBLS242.tsv: database_identifier, chemical_formula, smiles, inchi, metabolite_identification, chemical_shift, multiplicity, reliability, abundance และค่าสัญญาณรายตัวอย่าง',
            'Domain_2_sample_table_MTBLS242.tsv: Source Name, Sample Name, Characteristics[Organism], Characteristics[Sample type], Factor Value[time point]',
        ],
        fileStructure: [
            { name: 'Domain_2_NMR_results_MTBLS242.tsv', detail: 'TSV' },
            { name: 'Domain_2_sample_table_MTBLS242.tsv', detail: 'TSV' },
        ],
        analysisIdeas: [
            'Biomarker Discovery: ระบุ Biomarker จำนวนน้อยที่สุดที่วินิจฉัยได้แม่นยำ',
            'Predictive Model: สร้างแบบจำลองพยากรณ์โรคจากสารเมตาบอไลต์',
            'Differential Analysis: เปรียบเทียบสารเมตาบอไลต์ระหว่างผู้ป่วยกับกลุ่มควบคุม',
            'Correlation Analysis: วิเคราะห์ความสัมพันธ์ระหว่างสารเมตาบอไลต์กับข้อมูลกายภาพ',
            'Feature Selection: เลือกสารเมตาบอไลต์ที่สำคัญที่สุด',
        ],
        notes: [
            'ข้อมูลเชื่อมโยงกับโครงการ MTBLS242',
            'ข้อมูลผู้ป่วย: เบาหวาน + ความดันโลหิตสูง vs. กลุ่มควบคุม',
        ],
        githubUrl: `${GITHUB_ROOT}/nmr-result`,
    },
    {
        slug: 'hypertension',
        title: 'ชุดข้อมูล EMR ผู้ป่วยความดันแบบติดตามยาว',
        track: 'Medical',
        domains: ['Clinical', 'Cardiovascular Research'],
        sources: ['โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น'],
        totalRecords: 150000,
        sampledRecords: 100,
        fileTypes: ['xlsx'],
        summary: 'EMR ผู้ป่วยความดันโลหิตสูงประมาณ 150,000 คน ครอบคลุมสัญญาณชีพ Lab Comorbidity และยา ตามช่วงเวลา',
        overviewLabel: 'Hypertension EMR (XLSX, 150K patients, sampled 100)',
        overviewDescription: 'ข้อมูล longitudinal แบ่ง Period ทุก 60 วันรอบวันวินิจฉัย; มี Vitalsign, Lab (HbA1c, lipid), Comorbidity, ยา (ARB/CCB/ACEI); ใช้วิเคราะห์ประสิทธิภาพยา, พยากรณ์ความเสี่ยงหัวใจ/ไต',
        overview: [
            'ชุดข้อมูลผู้ป่วยโรคความดันโลหิตสูงจาก EMR จำนวนประมาณ 150,000 คน และมีตัวอย่าง 100 คน',
            'ข้อมูลบันทึกตลอดช่วงเวลา โดยแบ่งเป็น Periods ช่วงละ 60 วัน รอบวันที่วินิจฉัยโรค หรือ baseline / ht_onset',
        ],
        fields: [
            'ข้อมูลผู้ป่วย: age, sex, identify_by, ht_onset',
            'Vitalsign ตาม Period P: resp, o2sat, temp, hr, ht, wt, bmi, sbp, dbp',
            'Lab ตาม Period P: fpg, hba1c, wbc, platelet, hemoglobin, lipid profile, thyroid, troponin, proBNP, electrolytes',
            'Comorbidity ตาม Period P: arrhythmias, atrial_fibrillation, cad, dementia, hf, stroke, dm, ckd',
            'Medication ตาม Period P: ARB, CCB, ACEI, beta_blocker, diuretics, hydralazine, neprilysin_inhibitor',
        ],
        fileStructure: [
            { name: 'data_dictionary_hypertension_example.xlsx', detail: 'Excel (Data Dictionary)' },
        ],
        analysisIdeas: [
            'Risk Stratification: ประเมินความเสี่ยงภาวะแทรกซ้อน',
            'Cohort Analysis: วิเคราะห์ลักษณะผู้ป่วยกลุ่มต่างๆ',
            'Treatment Effectiveness: ประสิทธิภาพยาความดันแต่ละประเภท',
            'Predictive Model: พยากรณ์ความดันโลหิตหรือความเสี่ยงหัวใจ/ไต',
            'Trend Analysis: ติดตามแนวโน้ม SBP/DBP ตามเวลา',
        ],
        notes: ['ข้อมูลมีฟิลด์แบบ longitudinal ตาม Period P'],
        githubUrl: `${GITHUB_ROOT}/hypertension`,
    },
    {
        slug: 'diabetes',
        title: 'ชุดข้อมูล EMR ผู้ป่วยเบาหวานแบบติดตามยาว',
        track: 'Medical',
        domains: ['Clinical', 'Diabetes Research'],
        sources: ['โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น'],
        totalRecords: 70000,
        sampledRecords: 100,
        fileTypes: ['xlsx'],
        summary: 'EMR ผู้ป่วยเบาหวานประมาณ 70,000 คน ครอบคลุมข้อมูลผู้ป่วย สัญญาณชีพ Lab Comorbidity และยา',
        overviewLabel: 'Diabetes EMR (XLSX, 70K patients, sampled 100)',
        overviewDescription: 'ข้อมูล longitudinal แบ่ง Period ทุก 60 วัน; มี HbA1c, C-peptide, ยา (metformin/insulin/GLP-1); แบ่ง Type 1 ~2K, Type 2 ~50K, Unknown ~20K; ใช้จำแนกประเภท, พยากรณ์ HbA1c/แทรกซ้อน',
        overview: [
            'ชุดข้อมูลผู้ป่วยโรคเบาหวานจาก EMR จำนวนรวมประมาณ 70,000 คน และมีตัวอย่าง 100 คน',
            'ข้อมูลแบ่งเป็นเบาหวานประเภท 1 ประมาณ 2,000 คน, ประเภท 2 ประมาณ 50,000 คน และไม่ทราบประเภทประมาณ 20,000 คน',
            'ข้อมูลบันทึกตลอดช่วงเวลา โดยแบ่งเป็น Periods ช่วงละ 60 วัน รอบวันที่วินิจฉัยโรค หรือ baseline / dm_onset',
        ],
        fields: [
            'ข้อมูลผู้ป่วย: age, sex, identify_by, dm_onset, type1, type2, gdm',
            'Vitalsign ตาม Period P: resp, o2sat, temp, hr, ht, wt, bmi, sbp, dbp',
            'Lab ตาม Period P: fpg, hba1c, cpeptide, wbc, platelet, hemoglobin, lipid profile, thyroid, troponin, proBNP',
            'Comorbidity ตาม Period P: arrhythmias, atrial_fibrillation, cad, dementia, hf, stroke, ht, ckd',
            'Medication ตาม Period P: metformin, insulin, dapagliflozin, semaglutide, sitagliptin',
        ],
        fileStructure: [
            { name: 'data_dictionary_diabetes_example.xlsx', detail: 'Excel (Data Dictionary)' },
        ],
        analysisIdeas: [
            'Type Classification: จำแนกประเภทเบาหวาน Type 1 vs Type 2',
            'Risk Stratification: ประเมินความเสี่ยงภาวะแทรกซ้อน',
            'Treatment Recommendation: แนะนำแนวทางการรักษา',
            'Predictive Model: พยากรณ์ผลลัพธ์ทางคลินิก',
            'Medication Effectiveness: วิเคราะห์ประสิทธิภาพของยารักษาเบาหวาน',
            'Trend Analysis: ติดตามแนวโน้ม Lab/Vitalsign ตามเวลา',
        ],
        notes: ['ข้อมูลมีฟิลด์แบบ longitudinal ตาม Period P'],
        githubUrl: `${GITHUB_ROOT}/diabetes`,
    },
    {
        slug: 'ventilator',
        title: 'ชุดข้อมูลคลื่นของเครื่องช่วยหายใจจากผู้ป่วย ICU',
        track: 'Medical',
        domains: ['Clinical', 'ICU', 'Time Series'],
        sources: ['โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น'],
        totalRecords: null,
        sampledRecords: 17000,
        fileTypes: ['csv', 'json'],
        summary: 'คลื่น ventilator จาก ICU ครอบคลุม Flow, Pressure, Volume ที่ rate 25Hz พร้อมข้อมูลผู้ป่วย',
        overviewLabel: 'Ventilator Waveform (CSV/JSON, 17K records)',
        overviewDescription: 'สัญญาณ 3 แกน (Flow/Pressure/Volume) บันทึก 25 Hz, 24 ชั่วโมง/วัน, ติดต่อกัน 2-3 สัปดาห์ + patient demographics/diagnosis/handling; ใช้ตรวจจับความผิดปกติ, พยากรณ์ ICU stay, จำแนกโหมดการช่วยหายใจ',
        overview: [
            'ชุดข้อมูลคลื่นสัญญาณจากเครื่องช่วยหายใจของผู้ป่วยใน ICU โดยบันทึกข้อมูลทุกวันเป็นระยะเวลา 2-3 สัปดาห์',
            'ข้อมูลถูกบันทึก 24 ช่วงต่อวัน หรือ 1 ช่วงต่อชั่วโมง ที่ rate 25 Hz',
            'ข้อมูลประกอบด้วยคลื่นสัญญาณ 3 แกนหลัก: Flow, Pressure, Volume พร้อม demographics, diagnosis และ operation ของผู้ป่วย',
        ],
        fields: [
            'JSON: bed, captures, demographic, diagnosis, operation, patient, ven, time, raw_data',
            'CSV: Flow (l/min), Pressure (cmH2O), Volume (ml)',
        ],
        fileStructure: [
            { name: 'data_dictionary_smarticu.xlsx', detail: 'Excel (Data Dictionary)' },
            { name: 'smart_icu_data/', detail: 'Directory: ข้อมูล ventilator ตามผู้ป่วย' },
        ],
        analysisIdeas: [
            'Abnormality Detection: ตรวจจับความผิดปกติของคลื่นสัญญาณ ventilator',
            'Pattern Analysis: วิเคราะห์รูปแบบคลื่นหายใจ',
            'Clinical Decision Support: ช่วยแพทย์ตัดสินใจตั้งค่า ventilator',
            'Patient Status Prediction: พยากรณ์สถานะผู้ป่วยจากสัญญาณ',
            'ICU Length of Stay Prediction: พยากรณ์ระยะเวลาอยู่ใน ICU',
            'Breathing Mode Classification: จำแนกโหมดการช่วยหายใจ',
        ],
        notes: [
            'ข้อมูลเป็น time series แบบ high-frequency (25 Hz)',
            'จำนวนตัวอย่าง: 17,000 รายการ',
        ],
        githubUrl: `${GITHUB_ROOT}/ventilator`,
    },
    {
        slug: 'traffic',
        title: 'ชุดข้อมูลภาพกล้องจราจรเมืองขอนแก่น',
        track: 'Smart City',
        domains: ['Urban', 'Computer Vision', 'Traffic Analytics'],
        sources: ['Khon Kaen'],
        totalRecords: 60,
        sampledRecords: null,
        fileTypes: ['video', 'csv'],
        summary: 'วิดีโอ 35 คลิปจาก YouTube และสถิติ 25 จุดตรวจ พร้อมพิกัด GPS สำหรับวิเคราะห์จราจรเมืองขอนแก่น',
        overviewLabel: 'Traffic Video + Count Statistics (35 videos + 25 points)',
        overviewDescription: 'วิดีโอ 35 คลิปจาก YouTube + สถิติ 25 จุดตรวจ (แยก Car/Motorcycle/Truck พร้อมพิกัด GPS); ใช้ Unique Vehicle Counting, จำแนกประเภทยานพาหนะ, วิเคราะห์ความหนาแน่นตามพื้นที่/เวลา',
        overview: [
            'ชุดข้อมูลนี้ประกอบด้วย 2 ส่วนหลัก: วิดีโอจากกล้องตรวจจราจรจำนวน 35 คลิปจาก YouTube และข้อมูลสถิติการจราจรแบบตารางจำนวน 25 จุด จาก Khon Kaen Traffic Dashboard',
            'วิดีโอมุ่งเน้นโจทย์การนับยานพาหนะแบบไม่ซ้ำ (Unique Vehicle Counting) ส่วนข้อมูลสถิติเป็นข้อมูลนับยานพาหนะแยกประเภท รถยนต์ รถจักรยานยนต์ และรถบรรทุก พร้อมพิกัด GPS',
        ],
        fields: [
            'วิดีโอกล้องจราจร: ภาพการจราจรในมุมสูง ครอบคลุมจุดตัดและถนนสำคัญในเขตเมือง',
            'ข้อมูลสถิติการจราจร: ที่, เส้นทาง, ตำแหน่งติดตั้งเครื่องวัด, Lat, Lag, Car, Motorcycle, Truck, รวมต่อวัน, คัน/ชั่วโมง',
        ],
        fileStructure: [
            {
                name: '(วิดีโอจาก YouTube)',
                detail: 'คลิปวิดีโอกล้องจราจร 35 คลิป',
                url: 'https://www.youtube.com/playlist?list=PLTtSg8Z-ZIjopXh1ajC-Mx96Pp6xj-cjV',
            },
            {
                name: '(ข้อมูลจาก Dashboard)',
                detail: 'สถิติ 25 จุดตรวจ พร้อมพิกัด GPS และจำนวนยานพาหนะ',
                url: 'https://suchartstudio.github.io/kktraffic/',
            },
        ],
        analysisIdeas: [
            'Unique Vehicle Counting: นับจำนวนยานพาหนะที่ผ่านจุดตรวจโดยไม่ซ้ำ',
            'Vehicle Classification: จำแนกประเภทยานพาหนะ เช่น รถยนต์ รถจักรยานยนต์ รถบรรทุก และรถ buses',
            'Traffic Flow Analysis: วิเคราะห์ความหนาแน่นการจราจรตามช่วงเวลา',
            'Intersection Performance: ประเมินประสิทธิภาพของจุดตัดการจราจร',
            'Spatial Analysis: วิเคราะห์รูปแบบการจราจรตามพื้นที่ด้วยพิกัด GPS 25 จุด',
            'Cross-validation: เปรียบเทียบผลนับจากวิดีโอกับข้อมูลสถิติจากเครื่องวัด',
        ],
        notes: [
            'วิดีโอทั้งหมดมาจากแหล่ง YouTube เดียวกัน 35 คลิป',
            'ข้อมูลสถิติมาจาก KK Traffic Dashboard 25 จุดตรวจ',
            'ข้อมูลสถิติเป็นการนับฝั่งเดียว (single-lane) ไม่ใช่ทั้งสองฝั่งถนน',
        ],
        githubUrl: `${GITHUB_ROOT}/traffic`,
    },
    {
        slug: '3dpoints',
        title: 'ชุดข้อมูลสแกน 3 มิติ เมืองขอนแก่น',
        track: 'Smart City',
        domains: ['Urban', 'Computer Vision', '3D Point Cloud'],
        sources: ['Khon Kaen'],
        totalRecords: 1274,
        sampledRecords: 12,
        fileTypes: ['tar.gz'],
        summary: 'Point Cloud / Mesh ครอบคลุมพื้นที่เมือง แบ่งตาม tile พิกัด สำหรับวิเคราะห์โครงสร้างเมือง',
        overviewLabel: '3D Point Cloud / Mesh (tar.gz, 1,274 tiles, sampled 12)',
        overviewDescription: 'ข้อมูลสแกนเมืองขอนแก่นพร้อม texture และ metadata จัดเป็น Grid Tile; ใช้ตรวจจับวัตถุ 3D (อาคาร, ยานพาหนะ, ต้นไม้), วิเคราะห์ผังเมือง, เปรียบเทียบการเปลี่ยนแปลงพื้นที่',
        overview: [
            'ชุดข้อมูลนี้ประกอบด้วยไฟล์ 3D Model และ Point Cloud ที่ได้จากการสแกนพื้นที่เมือง',
            'ข้อมูลถูกแบ่งเป็น Tiles ตามพิกัด เช่น Tile_+010_+035 เพื่อการบริหารจัดการพื้นที่แบบ Grid',
        ],
        fields: [
            'ข้อมูลรูปแบบ 3D Point Cloud / Mesh ไม่มีฟิลด์แบบตาราง แต่มีโครงสร้างเป็นไฟล์แบบจำลอง 3D พร้อม texture และ metadata',
        ],
        fileStructure: [
            { name: '3D_KKC_sampled.tar.gz', detail: 'ไฟล์ข้อมูล 3D Scan (compressed)' },
            { name: 'Obj/Data/Tile_+010_+035/', detail: 'OBJ, MTL และ Texture JPG ตาม tile' },
            { name: 'Production_2/Scene/Data/Tile_p010_p035/', detail: 'ไฟล์ Scene แบบละเอียดและ metadata.xml' },
        ],
        analysisIdeas: [
            'การจัดการเมืองและวางผังเมือง: วิเคราะห์การใช้พื้นที่สาธารณะและโครงสร้างพื้นฐาน',
            'Object Detection ใน 3D Space: ตรวจจับและนับอาคาร ยานพาหนะ ต้นไม้',
            'Change Detection: เปรียบเทียบการเปลี่ยนแปลงของพื้นที่ระหว่างช่วงเวลา',
            'City Infrastructure Analysis: วิเคราะห์ถนน สะพาน และโครงสร้างพื้นฐาน',
        ],
        notes: [
            'ข้อมูลนี้เป็นตัวอย่างที่ sampled แล้ว',
            'ไฟล์ถูกจัดเก็บในรูปแบบ .tar.gz',
        ],
        githubUrl: `${GITHUB_ROOT}/3dpoints`,
    },
    {
        slug: 'complaints',
        title: 'ชุดข้อมูลบันทึกคำร้องจากประชาชน เทศบาลนครขอนแก่น',
        track: 'Smart City',
        domains: ['Urban', 'Civic Data', 'NLP'],
        sources: ['One Geo Survey, Ltd.', 'เทศบาลนครขอนแก่น'],
        totalRecords: 46189,
        sampledRecords: 462,
        fileTypes: ['xlsx'],
        summary: 'คำร้อง/ร้องเรียนของประชาชนประมาณ 46,000 รายการ ตั้งแต่รับเรื่องจนดำเนินการเสร็จสิ้น',
        overviewLabel: 'Municipal Complaints (XLSX, 46K records, sampled 462)',
        overviewDescription: 'คำร้องประชาชนต่อเทศบาลนครขอนแก่น พร้อมวันที่รับ-เสร็จ, เขต/ชุมชน, สถานะ, ส่วนงาน; ใช้ NLP จัดหมวดหมู่ข้อความ, วิเคราะห์ประสิทธิภาพการแก้ปัญหา, พยากรณ์วันเสร็จ, Heatmap ความหนาแน่นตามพื้นที่',
        overview: [
            'ชุดข้อมูลคำร้อง/ร้องเรียนของประชาชนต่อเทศบาลนครขอนแก่น จำนวนประมาณ 46,000 รายการ และมีตัวอย่าง 462 รายการ',
            'ข้อมูลบันทึกประวัติคำร้องตั้งแต่วันที่ได้รับจนกระทั่งดำเนินการเสร็จสิ้น',
        ],
        fields: [
            'ส่วนงาน, ฝ่าย, เลขคำร้อง, เรื่องร้องทุกข์, ประเภทคำร้อง, เขต, ชุมชน, วันที่รับเรื่อง, วันที่เสร็จ, สถานะ',
        ],
        fileStructure: [
            { name: 'ข้อมูลคำร้อง_sampled.xlsx', detail: 'Excel' },
        ],
        analysisIdeas: [
            'Text Classification: จัดหมวดหมู่คำร้องอัตโนมัติจากเนื้อหา',
            'NLP / Topic Modeling: วิเคราะห์ประเด็นร้องเรียนที่พบบ่อย',
            'Performance Analytics: วิเคราะห์ระยะเวลาในการดำเนินการ',
            'Geospatial Analysis: แผนที่ความหนาแน่นคำร้องตามเขต/ชุมชน',
            'Predictive Model: พยากรณ์วันเสร็จสิ้นหรือระบุส่วนงานที่เหมาะสม',
        ],
        notes: ['ข้อมูลเป็นตัวอย่างที่ sampled แล้ว'],
        githubUrl: `${GITHUB_ROOT}/complaints`,
    },
];

export function getDatasetBySlug(slug) {
    return datasetsData.find((dataset) => dataset.slug === slug) || null;
}
